# Site settings
author: Riley Moore
title: Riley Moore's Flatiron Blog
header-img: img/home-bg.png
email: rilemoore@gmail.com
copyright_name: Riley Moore
description: > # this means to ignore newlines until "baseurl:"
  Experiences and Challenges
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rilemoore

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
